## Adventures with Elephants

Description of the dataset:
---------------------------

This dataset has been recorded Angela S. Stoeger (angela.stoeger-horwath@univie.ac.at) from Vienna University and colleagues. Acoustic recordings were collected from three female and two male African elephants (Loxodonta africana) aged between 9 and 17 years located at Adventures with Elephants, Bela Bela, South Africa in 2011. The elephants were fully habituated to human presence and free to roam around in a savannah reserve of 300 ha. Vocalizations were recorded during two social contexts: spatial separation and subsequent bondings, recording distances between the elephant and the microphone ranged from 10 to several hundreds of meters. 
In 359 minutes of recordings we annotated 635 rumbles by manually tagging the beginning and the end of each rumble.

In [13]:
# annotations are in matlab file, which apparently is a hdf5 format
import scipy.io as sio

# source label annotations
filepath = '../../data/AdventuresWithElephants_Dataset/anno/groundTruth.mat'

# source location wav files
source_path = '../../data/AdventuresWithElephants_Dataset/wavs/all'
# target path
#dest_path = "../../data/AdventuresWithElephants_Dataset/wavs/samples/"
dest_path = "../../data/audio/serval-data/raw/elephants-angela"

annos = sio.loadmat(filepath)
data = annos['variable']

In [3]:
# r=[(x['SHAPE@XY'][i][0],x['SHAPE@XY'][i][1],x['PrimeKey'][i]) for i in range(x.shape[0])]
# unpack nd array
u = [(data[i,0][0],data[i,1][0][0],data[i,2][0][0],data[i,3][0]) for i in range(1,data.shape[0])]

In [4]:
# build dataframe from list
import pandas as pd
df = pd.DataFrame(data=u)  # 1st row as the column names
df.columns=['filename','start','duration','type']

Data format:
------------

Folder "wavs" contains all recorded signals (sampled at 44100Hz, 16bit, mono)

Folder "anno" contains the annotation in binary Matlab format (*.mat). The annotations include:

- groundTruth.mat: a cell that contains one annotated rumble in each row. The first column provides the name of the wav-file. The second column gives the start position of the rumble in samples; the third column contains the length of the annotated rumble in samples. The fourth column contains the type of rumble. There are two types (the usual "rumble" and the "snumble", which is a mixture of snort and rumble).

In [6]:
df['type'].value_counts()

rumble     607
snumble     11
Name: type, dtype: int64

In [5]:
# issue with EFAF2011A011.WAV en 012.WAV
df = df[df['filename'] != "EFAF2011A011.WAV"]
#df = df[df['filename'] != "EFAF2011A012.WAV"]
df = df.reset_index(drop=True)

In [7]:
# Code die aangeeft of de 10 seconden ervoor background is (1=ja, 0=nee)
df["background"] = 1
sr_target = 44100
# als (start-sr > 0) dan 0
df.loc[df["start"] < sr_target, "background"] = 0

In [8]:
for i in range(0, df.shape[0]):
    # skip 1e rij
    if(i==0):
        df.loc[i, "background"] = 0
    else:
        # Bereken eindtijd van vorige rij
        previous_end = df.loc[i-1, "start"] + df.loc[i-1, "duration"]
        # Check of filename zelfde is als file vorige rij
        if(df.loc[i-1, "filename"] == df.loc[i, "filename"]):
            # Check of previous end + sr_target*10 > start (dan 0)
            if(previous_end + sr_target*10 > df.loc[i, "start"]):
                #df.at[i,'ifor']
                df.loc[i, "background"] = 0
        else:
            df.loc[i, "background"] = 0

In [9]:
df['background'].value_counts()

0    312
1    306
Name: background, dtype: int64

In [10]:
df.iloc[210:213,]

filename     start  duration    type  background
210  EFAF2011A022.WAV  19995019    217364  rumble           1
211  EFAF2011A022.WAV  21145760    166217  rumble           1
212  EFAF2011A022.WAV  23240082    161622  rumble           1

In [15]:
# now we open the source file, cut out the piece that is annotated and save that as a 5 second sample
import sys, csv, os, shutil
import numpy as np

# we will also resample the original recordings
#import librosa
import soundfile as sf
import resampy

from tqdm import tqdm

# this is the sample reate we want
#sr_target = 44100
sr_target = 16000

fileList = []

# for each annotation do
for index,row in tqdm(df.iterrows(), total=len(df)):
    print("index: " + str(index))
    print("row: ")
    print(row)
    # map mat file contents
    source_filename = row.filename
    start = row.start
    duration = row.duration
    category = row.type
    print("source filename: " + source_filename)
    # read source wav 
    src_file_path = os.path.normcase("%s/%s" % (source_path,source_filename))
    print(src_file_path)
    # check if sourcefile exists
    if os.path.exists(src_file_path):
        # resample
        # Load audio file at its native sampling rate
        #x, sr_orig = librosa.load(src_file_path, mono=True, sr=None, dtype=np.int16)
        x, sr_orig = sf.read(src_file_path, dtype='int16')
        print("x: ")
        print(x)
        print("sr_orig: " + str(sr_orig))
        # We can resample this to any sampling rate we like, say 16000 Hz
        # define 5 seconds
        delta = 10 * sr_orig
        # clip from start to next 5 seconds resample in target sample rate
        y = resampy.resample(x[start:start + delta + 1], sr_orig, sr_target)
        print("y: ")
        print(y)
        # check if previous 5 secs is background
        # if so create a background sample
        if (row.background == 1):
            # clip from start to next 5 seconds resample in target sample rate
            yb = resampy.resample(x[start-delta:start+1], sr_orig, sr_target)
            print("yb class: " + str(yb))
            # make destination path
            b_dst_fname = "Background" + source_filename.split('.')[0] + '-' + str(round((start-delta)/sr_orig)) + '.' + source_filename.split('.')[1]
            # add meta data to list
            fileList.append([b_dst_fname,'background'])
            # path
            b_dst_file_path = "%s/%s" % (dest_path,b_dst_fname)
            # write it back
            #librosa.output.write_wav(b_dst_file_path, yb, sr_target)
            sf.write(b_dst_file_path, yb, sr_target)
        # make destination path
        dest_filename = "Elephant" + source_filename.split('.')[0] + '-' + str(round(start/sr_orig)) + '.' + source_filename.split('.')[1]
        dst_file_path = "%s/%s" % (dest_path,dest_filename)

        # create meta data file
        fileList.append([dest_filename,category])

        # write it back
        #librosa.output.write_wav(dst_file_path, y, sr_target)
        sf.write(dst_file_path, y, sr_target)
        #break;
    else:
        print('File %s not found.' % source_filename)
        break;

  0%|          | 0/618 [00:00<?, ?it/s]

index: 0
row: 
filename      EFAF2011A008.WAV
start                  1688633
duration                 51548
type                    rumble
background                   0
Name: 0, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100


  0%|          | 1/618 [00:02<24:32,  2.39s/it]

y: 
[   0    0    0 ... -458 -404 -584]
index: 1
row: 
filename      EFAF2011A008.WAV
start                  1829197
duration                 24136
type                    rumble
background                   0
Name: 1, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100


  0%|          | 2/618 [00:03<15:45,  1.54s/it]

y: 
[ 0  0  0 ... 23 12 15]
index: 2
row: 
filename      EFAF2011A008.WAV
start                  4925581
duration                 41697
type                    rumble
background                   1
Name: 2, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100
y: 
[-339 -624 -506 ...   30   13   24]
yb class: [-144 -274 -215 ... -439 -479 -611]


  0%|          | 3/618 [00:04<15:00,  1.46s/it]

index: 3
row: 
filename      EFAF2011A008.WAV
start                  7701919
duration                 41816
type                    rumble
background                   1
Name: 3, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100
y: 
[  0   0   0 ... -30 -21 -15]


  1%|          | 4/618 [00:05<14:31,  1.42s/it]

yb class: [ 0  0  0 ...  1 -7 -3]
index: 4
row: 
filename      EFAF2011A008.WAV
start                  7848265
duration                 44664
type                    rumble
background                   0
Name: 4, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100


  1%|          | 5/618 [00:06<13:01,  1.27s/it]

y: 
[ 76 192 105 ... -26   0  -4]
index: 5
row: 
filename      EFAF2011A008.WAV
start                  7917705
duration                 30799
type                    rumble
background                   0
Name: 5, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100


  1%|          | 6/618 [00:07<12:00,  1.18s/it]

y: 
[  0   0   0 ... -15 -21  -9]
index: 6
row: 
filename      EFAF2011A008.WAV
start                  8041171
duration                 57017
type                    rumble
background                   0
Name: 6, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100


  1%|          | 7/618 [00:07<11:16,  1.11s/it]

y: 
[  0   0   0 ... -32 -29 -68]
index: 7
row: 
filename      EFAF2011A008.WAV
start                 10693742
duration                 76558
type                    rumble
background                   1
Name: 7, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100
y: 
[  0   0   0 ... -14   0  -8]


  1%|▏         | 8/618 [00:09<11:28,  1.13s/it]

yb class: [ 0  0  0 ... 11  0  3]
index: 8
row: 
filename      EFAF2011A008.WAV
start                 10795225
duration                 65877
type                    rumble
background                   0
Name: 8, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100


  1%|▏         | 9/618 [00:09<10:57,  1.08s/it]

y: 
[0 0 0 ... 0 8 8]
index: 9
row: 
filename      EFAF2011A008.WAV
start                 10902049
duration                 35610
type                    rumble
background                   0
Name: 9, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100
y: 
[   0  -37 -124 ...    0  -19   -3]


  2%|▏         | 10/618 [00:11<11:10,  1.10s/it]

index: 10
row: 
filename      EFAF2011A008.WAV
start                 10982170
duration                 49850
type                    rumble
background                   0
Name: 10, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100


  2%|▏         | 11/618 [00:11<10:47,  1.07s/it]

y: 
[  0   0   0 ...  89  71 137]
index: 11
row: 
filename      EFAF2011A008.WAV
start                 11099678
duration                 30266
type                    rumble
background                   0
Name: 11, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100


  2%|▏         | 12/618 [00:12<10:26,  1.03s/it]

y: 
[  0   0   0 ...  24 -12  -1]
index: 12
row: 
filename      EFAF2011A008.WAV
start                 11211842
duration                 42729
type                    rumble
background                   0
Name: 12, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100


  2%|▏         | 13/618 [00:13<10:09,  1.01s/it]

y: 
[ 0  0  0 ... 19 16 26]
index: 13
row: 
filename      EFAF2011A008.WAV
start                 14807417
duration                 60554
type                    rumble
background                   1
Name: 13, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100
y: 
[   0    0    0 ... -139 -107 -141]


  2%|▏         | 14/618 [00:14<10:22,  1.03s/it]

yb class: [  0  -5   0 ...   5  -4 -11]
index: 14
row: 
filename      EFAF2011A008.WAV
start                 14887436
duration                 67045
type                    rumble
background                   0
Name: 14, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100


  2%|▏         | 15/618 [00:15<10:10,  1.01s/it]

y: 
[   0    0    0 ... -235 -210 -251]
index: 15
row: 
filename      EFAF2011A008.WAV
start                 15006383
duration                 45418
type                    rumble
background                   0
Name: 15, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100


  3%|▎         | 16/618 [00:15<09:57,  1.01it/s]

y: 
[  0   0   0 ... -11   0   3]
index: 16
row: 
filename      EFAF2011A008.WAV
start                 15118847
duration                 51905
type                    rumble
background                   0
Name: 16, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100


  3%|▎         | 17/618 [00:16<09:44,  1.03it/s]

y: 
[  0 -54 -14 ... -19 -31 -33]
index: 17
row: 
filename      EFAF2011A008.WAV
start                 15302677
duration                 47580
type                    rumble
background                   0
Name: 17, dtype: object
source filename: EFAF2011A008.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A008.WAV
x: 
[-53 -16 -15 ...  76  72  59]
sr_orig: 44100


  3%|▎         | 18/618 [00:17<09:33,  1.05it/s]

y: 
[ 0  0  0 ... 30 18 14]
index: 18
row: 
filename      EFAF2011A009.WAV
start                  2384341
duration                 61356
type                    rumble
background                   0
Name: 18, dtype: object
source filename: EFAF2011A009.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A009.WAV
x: 
[ 96 123 132 ...  13 -24 -15]
sr_orig: 44100


  3%|▎         | 19/618 [00:18<09:35,  1.04it/s]

y: 
[  0   0   0 ... 253 198 220]
index: 19
row: 
filename      EFAF2011A009.WAV
start                  6875450
duration                 23968
type                    rumble
background                   1
Name: 19, dtype: object
source filename: EFAF2011A009.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A009.WAV
x: 
[ 96 123 132 ...  13 -24 -15]
sr_orig: 44100
y: 
[   0    0    0 ... -104  -69  -72]
yb class: [ 51 148  97 ... -49 -24  -8]


  3%|▎         | 20/618 [00:19<09:45,  1.02it/s]

index: 20
row: 
filename      EFAF2011A009.WAV
start                  6942142
duration                 22923
type                    rumble
background                   0
Name: 20, dtype: object
source filename: EFAF2011A009.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A009.WAV
x: 
[ 96 123 132 ...  13 -24 -15]
sr_orig: 44100


  3%|▎         | 21/618 [00:20<09:36,  1.04it/s]

y: 
[0 0 0 ... 9 8 7]
index: 21
row: 
filename      EFAF2011A009.WAV
start                  7258396
duration                 29177
type                    rumble
background                   0
Name: 21, dtype: object
source filename: EFAF2011A009.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A009.WAV
x: 
[ 96 123 132 ...  13 -24 -15]
sr_orig: 44100


  4%|▎         | 22/618 [00:20<09:27,  1.05it/s]

y: 
[  0   0 -25 ...  -7 -22 -36]
index: 22
row: 
filename      EFAF2011A009.WAV
start                  7426162
duration                 16669
type                    rumble
background                   0
Name: 22, dtype: object
source filename: EFAF2011A009.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A009.WAV
x: 
[ 96 123 132 ...  13 -24 -15]
sr_orig: 44100


  4%|▎         | 23/618 [00:21<09:19,  1.06it/s]

y: 
[  0   0   0 ... -11  10 -25]
index: 23
row: 
filename      EFAF2011A010.WAV
start                  2791679
duration                 88077
type                    rumble
background                   0
Name: 23, dtype: object
source filename: EFAF2011A010.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A010.WAV
x: 
[-18 -31 -52 ... -17 -18 -39]
sr_orig: 44100
y: 
[ 0  0  0 ... 45 46 46]


  4%|▍         | 24/618 [00:22<09:25,  1.05it/s]

index: 24
row: 
filename      EFAF2011A010.WAV
start                  2969508
duration                 42782
type                    rumble
background                   0
Name: 24, dtype: object
source filename: EFAF2011A010.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A010.WAV
x: 
[-18 -31 -52 ... -17 -18 -39]
sr_orig: 44100


  4%|▍         | 25/618 [00:23<09:17,  1.06it/s]

y: 
[ 89 147  46 ...  -5   1 -15]
index: 25
row: 
filename      EFAF2011A010.WAV
start                  3176703
duration                 71301
type                    rumble
background                   0
Name: 25, dtype: object
source filename: EFAF2011A010.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A010.WAV
x: 
[-18 -31 -52 ... -17 -18 -39]
sr_orig: 44100


  4%|▍         | 26/618 [00:24<09:11,  1.07it/s]

y: 
[ 0 52  4 ... -4  0 -5]
index: 26
row: 
filename      EFAF2011A010.WAV
start                  3414932
duration                 67944
type                    rumble
background                   0
Name: 26, dtype: object
source filename: EFAF2011A010.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A010.WAV
x: 
[-18 -31 -52 ... -17 -18 -39]
sr_orig: 44100


  4%|▍         | 27/618 [00:24<09:04,  1.08it/s]

y: 
[  0   0   0 ... 279 244 251]
index: 27
row: 
filename      EFAF2011A010.WAV
start                  6506095
duration                 83706
type                    rumble
background                   1
Name: 27, dtype: object
source filename: EFAF2011A010.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A010.WAV
x: 
[-18 -31 -52 ... -17 -18 -39]
sr_orig: 44100
y: 
[-33 -89 -66 ... -14   1   1]
yb class: [   0  -13    0 ... -103  -82  -97]


  5%|▍         | 28/618 [00:26<09:14,  1.06it/s]

index: 28
row: 
filename      EFAF2011A010.WAV
start                  6884525
duration                 64012
type                    rumble
background                   0
Name: 28, dtype: object
source filename: EFAF2011A010.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A010.WAV
x: 
[-18 -31 -52 ... -17 -18 -39]
sr_orig: 44100


  5%|▍         | 29/618 [00:26<09:08,  1.07it/s]

y: 
[ 0  0  0 ... 33 14 24]
index: 29
row: 
filename      EFAF2011A010.WAV
start                 10222146
duration                 74317
type                    rumble
background                   1
Name: 29, dtype: object
source filename: EFAF2011A010.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A010.WAV
x: 
[-18 -31 -52 ... -17 -18 -39]
sr_orig: 44100
y: 
[  0   0   0 ... -17 -17 -13]


  5%|▍         | 30/618 [00:28<09:14,  1.06it/s]

yb class: [ 0  0  0 ... -1  1 -9]
index: 30
row: 
filename      EFAF2011A010.WAV
start                  7043876
duration                 35214
type                    rumble
background                   0
Name: 30, dtype: object
source filename: EFAF2011A010.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A010.WAV
x: 
[-18 -31 -52 ... -17 -18 -39]
sr_orig: 44100


  5%|▌         | 31/618 [00:28<09:08,  1.07it/s]

y: 
[ 0  0  7 ...  6 10  3]
index: 31
row: 
filename      EFAF2011A010.WAV
start                  7137029
duration                 49418
type                    rumble
background                   0
Name: 31, dtype: object
source filename: EFAF2011A010.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A010.WAV
x: 
[-18 -31 -52 ... -17 -18 -39]
sr_orig: 44100


  5%|▌         | 32/618 [00:29<09:02,  1.08it/s]

y: 
[  0   0   0 ... -17 -22 -40]
index: 32
row: 
filename      EFAF2011A010.WAV
start                 10534771
duration                 29084
type                    rumble
background                   1
Name: 32, dtype: object
source filename: EFAF2011A010.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A010.WAV
x: 
[-18 -31 -52 ... -17 -18 -39]
sr_orig: 44100
y: 
[   0  -39  -24 ... -159  -66   -9]


  5%|▌         | 33/618 [00:30<09:07,  1.07it/s]

yb class: [  0   0   0 ... -89 -56 -62]
index: 33
row: 
filename      EFAF2011A010.WAV
start                 10684693
duration                 38235
type                    rumble
background                   0
Name: 33, dtype: object
source filename: EFAF2011A010.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A010.WAV
x: 
[-18 -31 -52 ... -17 -18 -39]
sr_orig: 44100


  6%|▌         | 34/618 [00:31<09:01,  1.08it/s]

y: 
[  0   0   0 ... 709 636 662]
index: 34
row: 
filename      EFAF2011A010.WAV
start                 10790405
duration                 30363
type                    rumble
background                   0
Name: 34, dtype: object
source filename: EFAF2011A010.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A010.WAV
x: 
[-18 -31 -52 ... -17 -18 -39]
sr_orig: 44100


  6%|▌         | 35/618 [00:32<08:56,  1.09it/s]

y: 
[  0   0   0 ... -19 -11 -17]
index: 35
row: 
filename      EFAF2011A010.WAV
start                 13432313
duration                196077
type                    rumble
background                   1
Name: 35, dtype: object
source filename: EFAF2011A010.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A010.WAV
x: 
[-18 -31 -52 ... -17 -18 -39]
sr_orig: 44100
y: 
[-141 -355 -398 ...   -5   -6   -3]


  6%|▌         | 36/618 [00:33<09:00,  1.08it/s]

yb class: [   0    0    0 ...  -82  -73 -190]
index: 36
row: 
filename      EFAF2011A012.WAV
start                  4167674
duration                 37754
type                    rumble
background                   0
Name: 36, dtype: object
source filename: EFAF2011A012.WAV
../../data/AdventuresWithElephants_Dataset/wavs/all/EFAF2011A012.WAV
File EFAF2011A012.WAV not found.


In [16]:
# save the metadata for later
fileList
md = pd.DataFrame(fileList, columns=["filename", "category"])  
md.to_csv('./labels/custom/jungle/meta-data-elephant-adventures.csv',index=False)

In [17]:
md.tail()

filename    category
40    ElephantEFAF2011A010-239.WAV      rumble
41    ElephantEFAF2011A010-242.WAV      rumble
42    ElephantEFAF2011A010-245.WAV      rumble
43  BackgroundEFAF2011A010-295.WAV  background
44    ElephantEFAF2011A010-305.WAV      rumble

In [18]:
# copy all wavs to audio dir in serval
import glob
import shutil
import os

src_dir = "../../data/audio/serval-data/raw/elephants-angela"
dst_dir = "../../data/audio/serval-data/wav-16bit-16khz/elephants-angela"


for jpgfile in glob.iglob(os.path.join(src_dir, "*.WAV")):
    shutil.copy(jpgfile, dst_dir)
